version: 2

jobs:
        build:
                machine: true
                steps:
                        - checkout
                        - run: composer install
                        - run: verdor/bin/phpunit